# COMMAND_DONE_FROM_SERVE = "[COMMAND_DONE_FROM_SERVE]"
COMMAND_DONE_FROM_SERVE = "[STREAM_DONE]"
COMMAND_STOP_FROM_CLIENT = "[CLIENT_STOP]"
COMMAND_STREAM_START_FROM_SERVE = "[CHAT_STREAM_START]"

RAG_RETRIEVE_CHUNK_START = "retrieve_chunk_start"
RAG_RETRIEVE_CHUNK_DONE = "retrieve_chunk_done"

RAG_EVENT_IMAGE_QA_START = "generate_image_response_start"
RAG_EVENT_IMAGE_QA_DONE = "generate_image_response_doone"

RAG_EVENT_GENERATE_START = "generate_final_response_start"
